version: 1
disable_existing_loggers: False
formatters:
    simple:
        format: "[%(asctime)s] %(levelname)s %(name)s:%(filename)s:%(lineno)d: %(message)s"
        datefmt: "%Y-%m-%d %H:%M:%S"


handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: simple
        stream: ext://sys.stdout

    file_handler:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: simple
        filename: /var/log/walm/walm.log
        maxBytes: 10485760 # 10MB
        backupCount: 20
        encoding: utf8

loggers:
    my_module:
        level: INFO
        handlers: [console]
        propagate: no

root:
    level: INFO
    handlers: [console, file_handler]
