version: '2.0'

services:
  walm-db:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH}:/var/lib/mysql
    ports:
     - "13306:3306" 
    container_name: "walm-db"

  walm-app:
    image: "walm:last"
    command: ["walm","serv","--debug"]
    links:
      - walm-db:walm-db
    depends_on:
      - walm-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - WITH_DB_UNIT_TEST=1
      - WALM_DB_NAME=walm 
      - WALM_DB_USER=root
    ports:
     - "15000:5000" 
    container_name: "walm-app"
