version: '2.0'

services:
  db:
    image: hub.c.163.com/library/mysql:5.7
    container_name: mysql
    volumes:
      - /home/hanbing/myworkspace/go/src/walm/data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: zipkin
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 3306:3306
    networks: 
      - default 
      - app_net

  zipkin:
    image: openzipkin/zipkin:2.4.4
    container_name: zipkin
    environment:
      - STORAGE_TYPE=mysql
      # Point the zipkin at the storage backend
      - MYSQL_DB=zipkin
      - MYSQL_USER=root
      - MYSQL_PASS=123456
      - MYSQL_HOST=mysql
      - MYSQL_TCP_PORT=3306
      # Uncomment to enable scribe
      # - SCRIBE_ENABLED=true
      # Uncomment to enable self-tracing
      # - SELF_TRACING_ENABLED=true
      # Uncomment to enable debug logging
      # - JAVA_OPTS=-Dlogging.level.zipkin=DEBUG -Dlogging.level.zipkin2=DEBUG
    ports:
      # Port used for the Zipkin UI and HTTP Api
      - 9411:9411
      # Uncomment if you set SCRIBE_ENABLED=true
      # - 9410:9410
    networks: 
      - default 
      - app_net
networks: 
  app_net: 
    external: true
